app/Http/Controllers/Api/TelecommunicationApi.php, config/api.php, resources/views/telecommunication/tracking_number.blade.php
- separate base_uri and uri to support long format endpoint
=> - remove marker upon re-search msisdn

resources/views/_breadcrumb.blade.php, resources/views/_sidebar.blade.php, resources/views/_template_authorized.blade.php, resources/views/e_ktp/search_by_nkk.blade.php, resources/views/transportasi/cek_kendaraan.blade.php
- Tweak searchbar cek kendaraan
- Tweak not working breadcrumbs
- Tweak some padding and icon
=> Style Fix : Search bar Cek Kendaraan and some tweak style

resources/views/_breadcrumb.blade.php, resources/views/_sidebar.blade.php, resources/views/_template_authorized.blade.php, resources/views/e_ktp/search_by_nik.blade.php, resources/views/e_ktp/search_by_nkk.blade.php, resources/views/transportasi/cek_kendaraan.blade.php
[Fix Style : Add toast example Modul Search NIK and tweak table response](https://github.com/virtualynx/f-sharp-explore/commit/0cd4f56844b327e1b882955e345a89901b9de517)
=> Fix Style : Add toast example Modul Search NIK and tweak table response 

resources/views/__template_base.blade.php
=> Style Fix : Add Spinner

resources/views/__template_base.blade.php
Fix Style : Tweak Spinner Center
=> Fix Style : Tweak Spinner Center

resources/views/transportasi/cek_kendaraan.blade.php
Fix Style : Searchbar Cek Kendaraan
=> Fix Style : Searchbar Cek Kendaraan

resources/views/e_ktp/search_by_nik.blade.php, resources/views/e_ktp/search_by_nkk.blade.php
Improvement : simplify RT / RW menu search dukcapil
=> Improvement : simplify RT / RW menu search dukcapil

resources/views/e_ktp/search_by_nik.blade.php, resources/views/e_ktp/search_by_nkk.blade.php, resources/views/transportasi/cek_kendaraan.blade.php
- Table style add new feature (hover, right panel refresh and fullsceen)
- Tweak menu cek kendaraan (table style and searchbar style)
=> Style Fix : Tweak table style and tweak menu cek kendaraan

resources/views/transportasi/cek_kendaraan.blade.php
Fix Style : Cek kendaraan Table Style
=> Fix Style : Cek kendaraan Table Style

resources/views/telecommunication/locate_number.blade.php
=> Style Fix : Style Fix Menu Locate Number

resources/views/_breadcrumb.blade.php, resources/views/_sidebar.blade.php, resources/views/e_ktp/search_by_nik.blade.php, resources/views/e_ktp/search_by_nkk.blade.php, resources/views/telecommunication/locate_number.blade.php, resources/views/telecommunication/telco_registration.blade.php, resources/views/transportasi/cek_kendaraan.blade.php
- Fix Style Telco Regis
- Tweak Breadcrumbs
- Table standart (bold, padding, etc)
=> Style Fix : Style Fix Menu Telco Registration, Table Standardization

resources/views/e_ktp/search_by_nik.blade.php, resources/views/e_ktp/search_by_nkk.blade.php, resources/views/telecommunication/telco_registration.blade.php
Bug Fix : Searchbar Telco Bug Fix And Adjust Width NKK NIK
=> Bug Fix : Searchbar Telco Bug Fix And Adjust Width NKK NIK

resources/views/__template_base.blade.php, resources/views/home.blade.php, resources/views/telecommunication/telco_registration.blade.php
=> Style : Dummy Dashboard Page

resources/views/home.blade.php
Style Fix : Add Dropdown On Maps Stats
=> Style Fix : Add Dropdown On Maps Stats

resources/views/_navbar.blade.php
=> Bug Fix : New Logo

app/Http/Controllers/EKtpController.php, app/Models/SearchLogDukcapil.php, composer.json, composer.lock, resources/views/_sidebar.blade.php, resources/views/e_ktp/search_by_profile.blade.php, routes/web.php
Note: ini baru datatable nya dulu. untuk klik data detail belum
=> feat(dukcapil): add module search by profile

resources/views/e_ktp/search_by_profile.blade.php
Bug Fix : Datatable Search By Profile
=> Bug Fix : Datatable Search By Profile

app/Http/Controllers/Api/TelecommunicationApi.php, resources/views/telecommunication/tracking_number.blade.php, resources/views/telecommunication/tracking_number/modal_add_edit_number.php, resources/views/telecommunication/tracking_number/modal_set_geofence.php, resources/views/telecommunication/tracking_number/modal_tracking_log.php
Style Fix : Modal Style Fix Menu Tracking Number
=> Style Fix : Modal Style Fix Menu Tracking Number

resources/views/telecommunication/tracking_number.blade.php, resources/views/telecommunication/tracking_number/modal_tracking_log.php
Style Fix : Modal Maps Style Padding On "tracking number"
=> Style Fix : Modal Maps Style Padding On "tracking number"

app/Http/Controllers/Api/TelecommunicationApi.php
Style Fix : icon eye ketinggalan (modal tracking log) Maaf :)
=> Style Fix : icon eye ketinggalan (modal tracking log) Maaf :)

resources/views/login.blade.php, resources/views/register.blade.php
Style Fix : Tweak Padding Form Auth.
=> Style Fix : Tweak Padding Form Auth.

resources/views/dataleak/data-gmail.blade.php, resources/views/dataleak/data-leak.blade.php, resources/views/dataleak/data-sosmed.blade.php, resources/views/e_ktp/search_by_nik.blade.php, resources/views/e_ktp/search_by_nkk.blade.php, resources/views/e_ktp/search_by_profile.blade.php, resources/views/telecommunication/tracking_imsi_imei.blade.php, resources/views/transportasi/cek_kendaraan.blade.php
Style Fix : Change All "Text Search"
=> Style Fix : Change All "Text Search"

public/webtools/Address.html, public/webtools/Breaches.html, public/webtools/Business.html, public/webtools/Communities.html, public/webtools/Currencies.html, public/webtools/Documents.html, public/webtools/Domain.html, public/webtools/Email.html, public/webtools/Facebook.html, public/webtools/IP.html, public/webtools/Images.html, public/webtools/Instagram.html, public/webtools/LinkedIn.html, public/webtools/Location.html, public/webtools/Name.html, public/webtools/Pastes.html, public/webtools/Radio.html, public/webtools/Search.html, public/webtools/Telephone.html, public/webtools/Twitter.html, public/webtools/Username.html, public/webtools/Vehicle.html, public/webtools/Video.html, public/webtools/Videos.html, public/webtools/index.html, resources/views/_sidebar.blade.php
Bug Fix : Style and JS no load (webtools) And Tweak Padding Sidebar
=> Bug Fix : Style and JS no load (webtools) And Tweak Padding Sidebar

public/webtools/index.html, public/webtools/style.css
Style Fix : Change Webtools Light Theme
=> Style Fix : Change Webtools Light Theme

public/webtools/index.html
=> Style Fix : Table Webtool Fix

public/webtools/style.css
Fix Style : Change Default Color Sidebar Webtools
=> Fix Style : Change Default Color Sidebar Webtools

resources/views/dataleak/data-sosmed.blade.php
Fix Style : Data Sosmed Footer
=> Fix Style : Data Sosmed Footer

resources/views/e_ktp/search_by_nik.blade.php
=> Append Fix NIK Result

resources/views/dataleak/data-sosmed.blade.php
Fix Style : Leak Media Social - Searchbar consistently
=> Fix Style : Leak Media Social - Searchbar consistently
